"""competitor, source, snapshot, extraction, finding

Revision ID: 2e55055c20e3
Revises: 03b433249b1c
Create Date: 2026-09-14 14:30:17.724772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e55055c20e3'
down_revision: Union[str, Sequence[str], None] = '03b433249b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'muted', name='competitor_status'), nullable=False),
    sa.Column('muted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_workspace_id'), 'competitor', ['workspace_id'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('website', 'pricing_page', 'rss', 'reddit', 'hackernews', 'producthunt', 'youtube', 'github', 'appstore', 'playstore', name='source_type'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('crawl_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('healthy', 'degraded', 'failing', 'blocked', name='source_status'), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('blocked_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_competitor_id'), 'source', ['competitor_id'], unique=False)
    op.create_index('ix_source_status_last_attempt_at', 'source', ['status', 'last_attempt_at'], unique=False)
    op.create_index(op.f('ix_source_workspace_id'), 'source', ['workspace_id'], unique=False)
    op.create_table('snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('raw_payload_dropped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshot_source_id_fetched_at', 'snapshot', ['source_id', sa.literal_column('fetched_at DESC')], unique=False)
    op.create_index(op.f('ix_snapshot_workspace_id'), 'snapshot', ['workspace_id'], unique=False)
    op.create_table('extraction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('method', sa.Enum('selector', 'llm', 'mixed', name='extraction_method'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_extraction_workspace_id'), 'extraction', ['workspace_id'], unique=False)
    op.create_table('finding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.Enum('pricing', 'feature_launch', 'messaging', 'hiring', 'funding', 'partnership', 'content', 'other', name='change_type'), nullable=False),
    sa.Column('urgency', sa.Enum('high', 'medium', 'low', name='urgency'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('changeset', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('dedupe_key', sa.String(), nullable=False),
    sa.Column('classification_status', sa.Enum('ok', 'pending', 'failed', name='classification_status'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finding_workspace_competitor_detected_at', 'finding', ['workspace_id', 'competitor_id', sa.literal_column('detected_at DESC')], unique=False)
    op.create_index('ix_finding_workspace_dedupe_key', 'finding', ['workspace_id', 'dedupe_key'], unique=False)
    op.create_index(op.f('ix_finding_workspace_id'), 'finding', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finding_workspace_id'), table_name='finding')
    op.drop_index('ix_finding_workspace_dedupe_key', table_name='finding')
    op.drop_index('ix_finding_workspace_competitor_detected_at', table_name='finding')
    op.drop_table('finding')
    op.drop_index(op.f('ix_extraction_workspace_id'), table_name='extraction')
    op.drop_table('extraction')
    op.drop_index(op.f('ix_snapshot_workspace_id'), table_name='snapshot')
    op.drop_index('ix_snapshot_source_id_fetched_at', table_name='snapshot')
    op.drop_table('snapshot')
    op.drop_index(op.f('ix_source_workspace_id'), table_name='source')
    op.drop_index('ix_source_status_last_attempt_at', table_name='source')
    op.drop_index(op.f('ix_source_competitor_id'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_competitor_workspace_id'), table_name='competitor')
    op.drop_table('competitor')
    # ### end Alembic commands ###
    sa.Enum(name='classification_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='urgency').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='change_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='extraction_method').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='source_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='source_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='competitor_status').drop(op.get_bind(), checkfirst=True)
