"""notification_channel, routing_rule, alert, digest

Revision ID: 8786456251a3
Revises: f1a2b3c4d5e6
Create Date: 2026-09-15 20:27:18.245472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8786456251a3'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digest',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finding_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'period_start', 'period_end', name='uq_digest_workspace_period')
    )
    op.create_index(op.f('ix_digest_workspace_id'), 'digest', ['workspace_id'], unique=False)
    op.create_table('notification_channel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('email', 'slack', 'webhook', name='channel_kind'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_channel_workspace_id'), 'notification_channel', ['workspace_id'], unique=False)
    op.create_table('routing_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=True),
    sa.Column('change_type', postgresql.ENUM('pricing', 'feature_launch', 'messaging', 'hiring', 'funding', 'partnership', 'content', 'other', name='change_type', create_type=False), nullable=True),
    sa.Column('min_urgency', postgresql.ENUM('high', 'medium', 'low', name='urgency', create_type=False), nullable=False),
    sa.Column('channels', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_routing_rule_workspace_competitor', 'routing_rule', ['workspace_id', 'competitor_id'], unique=False)
    op.create_index(op.f('ix_routing_rule_workspace_id'), 'routing_rule', ['workspace_id'], unique=False)
    op.create_table('alert',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='alert_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'channel_id', name='uq_alert_finding_channel')
    )
    op.create_index('ix_alert_status_created_at', 'alert', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_alert_workspace_id'), 'alert', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_workspace_id'), table_name='alert')
    op.drop_index('ix_alert_status_created_at', table_name='alert')
    op.drop_table('alert')
    sa.Enum(name='alert_status').drop(op.get_bind(), checkfirst=True)

    op.drop_index(op.f('ix_routing_rule_workspace_id'), table_name='routing_rule')
    op.drop_index('ix_routing_rule_workspace_competitor', table_name='routing_rule')
    op.drop_table('routing_rule')

    op.drop_index(op.f('ix_notification_channel_workspace_id'), table_name='notification_channel')
    op.drop_table('notification_channel')
    sa.Enum(name='channel_kind').drop(op.get_bind(), checkfirst=True)

    op.drop_index(op.f('ix_digest_workspace_id'), table_name='digest')
    op.drop_table('digest')
    # ### end Alembic commands ###
