"""source extraction failure streak

Revision ID: c02973847365
Revises: 2e55055c20e3
Create Date: 2026-09-15 19:26:44.146486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02973847365'
down_revision: Union[str, Sequence[str], None] = '2e55055c20e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'source',
        sa.Column('extraction_failure_streak', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'extraction_failure_streak')
    # ### end Alembic commands ###
